CREATE DATABASE Desafio_Pluft
USE Desafio_Pluft

CREATE TABLE TIPO_ESTABELECIMENTO(
	Id INT IDENTITY PRIMARY KEY,
	Tipo varchar(100) not null
);


CREATE TABLE TIPO_USUARIO(
	Id INT IDENTITY PRIMARY KEY,
	Tipo varchar(100) not null
);


CREATE TABLE STATUS_AGENDAMENTO(
	Id INT IDENTITY PRIMARY KEY,
	Nome varchar(100) not null
);



CREATE TABLE ESTABELECIMENTOS(
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(255) NOT NULL,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	Id_Tipo_Estabelec INT FOREIGN KEY REFERENCES TIPO_ESTABELECIMENTO(Id),
	Endereco VARCHAR(255) NOT NULL,
	Horario_Funcionamento VARCHAR(255),
	Vagas VARCHAR(255) NOT NULL
);

CREATE TABLE USUARIOS(
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(255) NOT NULL,
	Telefone VARCHAR(20),
    Data_Criacao DATETIME NOT NULL,
	Id_Estabelecimento INT FOREIGN KEY REFERENCES ESTABELECIMENTOS(Id),
	Id_Tipo_Usuario INT FOREIGN KEY REFERENCES TIPO_USUARIO(Id)
);

CREATE TABLE CLIENTES(
	Id INT IDENTITY PRIMARY KEY,
	CPF CHAR(11) NOT NULL UNIQUE,
	Data_Nascimento DATETIME NOT NULL,
	RG CHAR(9) NOT NULL UNIQUE,
	Endereco VARCHAR(255) NOT NULL,
	Id_Usuario INT FOREIGN KEY REFERENCES USUARIOS(Id),
);

CREATE TABLE LOJISTAS(
	Id INT IDENTITY PRIMARY KEY,
	CPF CHAR(11) NOT NULL UNIQUE,
	Data_Nascimento DATETIME NOT NULL,
	RG CHAR(9) NOT NULL UNIQUE,
	Endereco VARCHAR(255) NOT NULL,
	Id_Usuario INT FOREIGN KEY REFERENCES USUARIOS(Id)
);

CREATE TABLE AGENDAMENTOS(
	Id INT IDENTITY PRIMARY KEY,
	Id_Cliente INT FOREIGN KEY REFERENCES CLIENTES(Id),
	Id_Estabelecimento INT FOREIGN KEY REFERENCES ESTABELECIMENTOS(Id),
	Id_Status INT FOREIGN KEY REFERENCES STATUS_AGENDAMENTO(Id),
	Id_Lojista INT FOREIGN KEY REFERENCES LOJISTAS(Id),
	Data_Criacao DATETIME NOT NULL,
	Data_Agendamento DATETIME NOT NULL
);

CREATE TABLE PRODUTOS(
	Id int identity primary key,
	Titulo VARCHAR(100) not null,
	Descricao VARCHAR(255),
	Preco money not null,
	QtdEstoque int not null,
	Id_Estabelec INT FOREIGN KEY REFERENCES ESTABELECIMENTOS(Id)

);

CREATE TABLE PRODUTO_AGENDAMENTOS(
	Id int identity primary key,
	Id_Agendamento int foreign key references AGENDAMENTOS(Id),
	Id_Produtos int foreign key references PRODUTOS(Id),
);
